/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertThat(classUnderTest.getGreeting()).isNotEqualTo("app should have a greeting");
    }
}
